# Generated by Django 4.2.11 on 2025-09-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price_local', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('category', models.CharField(max_length=30)),
                ('supplier_country', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
